ShowPin.MvcPaging.Demo/Models/Product.cs
namespace ShowPin.MvcPaging.Demo.Models
{
    public class Product
    {
        public string Name { get; set; }
        public string Category { get; set; }
    }
}

ShowPin.MvcPaging.Demo/Models/SearchModel.cs
namespace ShowPin.MvcPaging.Demo.Models
{
    public class SearchModel
    {
        public int? Page { get; set; }

        public SearchModel()
        {
            Page = 1;
        }
    }
}

ShowPin.MvcPaging.Demo/Areas/PagingArea/Controllers/PagingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShowPin.MvcPaging.Demo.Models;

namespace ShowPin.MvcPaging.Demo.Areas.PagingArea.Controllers
{
    public class PagingController : Controller
    {
        int _currentPage = 1;
        int _pageSize = 10;
        private readonly string[] _allCategories = { "吃的", "穿的", "用的" };
        private readonly IList<Product> _allProducts = new List<Product>();

        public PagingController()
        {
            InitializeProducts();
        }

        //简单初始化产品集合
        private void InitializeProducts()
        {
            for (var i = 0; i < 122; i++)
            {
                var product = new Product
                {
                    Name = "产品 " + (i + 1)
                };
                var categoryIndex = i % 4;
                if (categoryIndex > 2)
                {
                    categoryIndex = categoryIndex - 3;
                }
                product.Category = _allCategories[categoryIndex];
                _allProducts.Add(product);
            }
        }
        public ActionResult Index(int? page = 1, int? size = 10)
        {
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;

            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            return View(model);
        }
    }
}

ShowPin.MvcPaging.Demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShowPin.MvcPaging.Demo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ShowPin.MvcPaging.Demo/Controllers/PagingController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ShowPin.MvcPaging.Demo.Models;

namespace ShowPin.MvcPaging.Demo.Controllers
{
    public class PagingController : Controller
    {
        int _currentPage = 1;
        int _pageSize = 10;
        private readonly string[] _allCategories = { "吃的", "穿的", "用的" };
        private readonly IList<Product> _allProducts = new List<Product>();

        public PagingController()
        {
            InitializeProducts();
        }

        //简单初始化产品集合
        private void InitializeProducts()
        {
            for (var i = 0; i < 122; i++)
            {
                var product = new Product
                {
                    Name = "产品 " + (i + 1)
                };
                var categoryIndex = i % 4;
                if (categoryIndex > 2)
                {
                    categoryIndex = categoryIndex - 3;
                }
                product.Category = _allCategories[categoryIndex];
                _allProducts.Add(product);
            }
        }


        //简单的分页
        public ActionResult Index(int? page = 1, int? size = 10)
        {
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;

            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            return View(model);
        }

        //根据产品分类搜索分页
        public ActionResult PagingByCategory(string categoryName, int? page = 1, int? size = 10)
        {
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;

            categoryName = categoryName ?? _allCategories[0];
            var model = _allProducts.Where(m => m.Category == categoryName)
                .ToPagedList(_currentPage, _pageSize);

            ViewBag.CategoryName = new SelectList(_allCategories, categoryName);
            ViewBag.CategoryDisplayName = categoryName;
            return View(model);
        }

        //根据多个产品分类搜索分页
        public ActionResult PagingByCategories(string[] categories, int? page = 1, int? size = 10)
        {
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;

            categories = categories ?? new string[0];
            var model = _allProducts.Where(m => categories.Contains(m.Category))
               .ToPagedList(_currentPage, _pageSize);
            ViewBag.AllCategories = _allCategories;
            ViewBag.SelectedCategories = categories;
            return View(model);
        }

        //使用路由名称分页
        public ActionResult PagingByRoute()
        {
            return View();
        }

        //使用路由名称分页，为了模拟这种特殊的需求，所以使用了特殊的方式
        public ActionResult ShowPagingByRoute(int? page = 1, int? size = 10)
        {
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;

            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            return PartialView("_PartialPagingByRoute", model);
        }

        //ajax分页
        public ActionResult Ajax()
        {
            return View();
        }

        //ajax分页
        public ActionResult AjaxPage(int? page = 1, int? size = 10)
        {
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;

            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            return PartialView("_ProductGrid", model);
        }

        //自定义模版
        public ActionResult Bootstrap(int? page = 1, int? size = 10)
        {
            _currentPage = page.HasValue ? page.Value : _currentPage;
            _pageSize = size.HasValue ? size.Value : _pageSize;

            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            return View(model);
        }

        //自定义页码路由键值对
        public ActionResult CustomPageRouteValueKey(SearchModel search)
        {
            if (search.Page != null) _currentPage = (int)search.Page;
            var model = _allProducts.ToPagedList(_currentPage, _pageSize);
            return View(model);
        }
    }
}

ShowPin.MvcPaging.Demo/Areas/PagingArea/Views/Paging/Index.cshtml
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <thead>
        <tr>
            <th>产品名称</th>
            <th>分类名称</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Source)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>
        }
    </tbody>
</table>
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination pagination-large" }))

ShowPin.MvcPaging.Demo/Areas/PagingArea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShowPin.MvcPaging.Demo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ShowPin.MvcPaging.Demo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ShowPin.MvcPaging.Demo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron hide">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row hide">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <ol class="round">
            <li class="one">
                <h5>简单的分页</h5>
                一个产品列表分页的简单例子。@Html.ActionLink("点击这里查看演示", "Index", "Paging")
            </li>

            <li class="two">
                <h5>带搜索参数的例子（一）</h5>
                根据产品分类搜索分页的例子。@Html.ActionLink("点击这里查看演示", "PagingByCategory", "Paging")
            </li>

            <li class="three">
                <h5>带搜索参数的例子（二）</h5>
                根据多个产品分类搜索分页的例子。@Html.ActionLink("点击这里查看演示", "PagingByCategories", "Paging")
            </li>
            <li class="four">
                <h5>在 Area 里使用简单的分页</h5>
                在 Area 里使用简单的分页的例子。@Html.ActionLink("点击这里查看演示", "Index", "Paging", new { Area = "PagingArea" }, null)
            </li>
            <li class="five">
                <h5>Ajax 分页</h5>
                Ajax 分页的例子。@Html.ActionLink("点击这里查看演示", "Ajax", "Paging")
            </li>
            <li class="six">
                <h5>使用自定义模版分页</h5>
                使用自定义模版分页的例子。@Html.ActionLink("点击这里查看演示", "Bootstrap", "Paging")
            </li>
            <li class="seven">
                <h5>使用自定的分页键分页</h5>
                使用自定义的分页键代替默认的分页键。@Html.ActionLink("点击这里查看演示", "CustomPageRouteValueKey", "Paging")
            </li>
            <li class="eight">
                <h5>使用路由名称分页</h5>
                使用路由名称分页的例子。@Html.ActionLink("点击这里查看演示", "PagingByRoute", "Paging")
            </li>
        </ol>
    </div>
</div>

ShowPin.MvcPaging.Demo/Views/Paging/Ajax.cshtml
@{
    ViewBag.Title = "Ajax 分页";
}
<h2>浏览所有产品——Ajax 分页的例子</h2>
<div id="gridcontainer">
    @{Html.RenderAction("AjaxPage", "Paging");}
</div>
@section scripts{
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
}

ShowPin.MvcPaging.Demo/Views/Paging/Bootstrap.cshtml
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>
@{
    ViewBag.Title = "使用自定义模版分页";
}
<h2>浏览所有产品——使用自定义模版分页的例子</h2>
<table class="table">
	<thead>
		<tr>
			<th>产品名称</th>
			<th>分类名称</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var product in Model.Source)
  { 
			<tr>
				<td>@product.Name</td>
				<td>@product.Category</td>
			</tr>
  }
	</tbody>
</table>
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination pagination-large" }).DisplayTemplate("BootstrapPagination"))

ShowPin.MvcPaging.Demo/Views/Paging/CustomPageRouteValueKey.cshtml
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>
@{
    ViewBag.Title = "自定义页码路由键值对";
}
<h2>浏览所有产品——使用自定义的分页键代替默认的分页键</h2>
<table class="table">
    <thead>
        <tr>
            <th>产品名称</th>
            <th>分类名称</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Source)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>
        }
    </tbody>
</table>
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination pagination-large" }).PageRouteValueKey("Search.page"))

ShowPin.MvcPaging.Demo/Views/Paging/Index.cshtml
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>
@{
    ViewBag.Title = "简单的分页";
}
<h2>浏览所有产品——简单的分页</h2>
<table class="table">
    <thead>
        <tr>
            <th>产品名称</th>
            <th>分类名称</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Source)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>
        }
    </tbody>
</table>
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination pagination-large" }))

ShowPin.MvcPaging.Demo/Views/Paging/PagingByCategories.cshtml
@using System.Linq
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>
@{
    ViewBag.Title = "带搜索参数的例子（二）";
}
<h2>根据分类浏览产品——根据多个产品分类搜索分页</h2>
@using (Html.BeginForm("PagingByCategories",

"Paging", FormMethod.Get))
{
		<p>选择产品分类</p>
		<ul>
			@{
    IEnumerable<string> selectedCategories = ViewBag.SelectedCategories ?? new string[0];
			}
			@foreach (var category in ViewBag.AllCategories)
   {
				<li>
					<label>
						<input type="checkbox" name="categories" value="@category" @if

(selectedCategories.Any(c => c == category))
                                                                 { <text> checked="checked"</text>} />
						@category
					</label>
				</li>
   }
		</ul>
		<input type="submit" value="提交" />
}
@if (Model.Source.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>产品名称</th>


                <th>分类名称</th>
            </tr>
        </thead>
        <tbody>


            @foreach (var product in Model.Source)
            {
                <tr>
                    <td>@product.Name</td>


                    <td>@product.Category</td>
                </tr>
            }
        </tbody>
    </table>
	@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o

=> o.HtmlAttributes(new { @class = "pagination pagination-large" }).RouteValues(new
{
    categories = ViewBag.SelectedCategories

}))
}

ShowPin.MvcPaging.Demo/Views/Paging/PagingByCategory.cshtml
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>
@{
    ViewBag.Title = "带搜索参数的例子（一）";
}
<h2>根据分类浏览产品——根据产品分类搜索分页</h2>
@using (Html.BeginForm("PagingByCategory", "Paging", FormMethod.Get))
{
	<p>
		选择产品分类：
		@Html.DropDownList("categoryName")
		<input type="submit" value="提交" />
	</p>
}
@if (Model.TotalItemCount > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>产品名称</th>
                <th>分类名称</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Source)
            {
                <tr>
                    <td>@product.Name</td>
                    <td>@product.Category</td>
                </tr>
            }
        </tbody>
    </table>
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination pagination-large" }).RouteValues(new { categoryname = ViewBag.CategoryDisplayName }))
}

ShowPin.MvcPaging.Demo/Views/Paging/PagingByRoute.cshtml
@{
    ViewBag.Title = "浏览所有产品";
}
<h2>@ViewBag.Title——使用路由名称分页的例子</h2>
@{Html.RenderAction("ShowPagingByRoute", "Paging");}

ShowPin.MvcPaging.Demo/Views/Shared/DisplayTemplates/BootstrapPagination.cshtml
@using ShowPin.MvcPaging
@model PaginationModel


@BuildLink()


@helper  BuildLink()
{
    var ul = new TagBuilder("ul");
    ul.MergeAttributes(Model.Options.HtmlAttributes);
    foreach (var link in Model.PaginationLinks)
    {
        var liBuilder = new TagBuilder("li");
        if (link.IsCurrent)
        {
            liBuilder.MergeAttribute("class", "active");
        }
        if (!link.IsEnabled)
        {
            liBuilder.MergeAttribute("class", "disabled");
        }

        var aBuilder = new TagBuilder("a");
        aBuilder.MergeAttribute("href", link.Url ?? "javascript:");

        // Ajax support
        if (Model.AjaxOptions != null)
        {
            foreach (var ajaxOption in Model.AjaxOptions.ToUnobtrusiveHtmlAttributes())
            {
                aBuilder.MergeAttribute(ajaxOption.Key, ajaxOption.Value.ToString(), true);
            }
        }


        switch (link.DisplayText)
        {
            case "«":
                aBuilder.SetInnerText("←");
                break;
            case "»":
                aBuilder.SetInnerText("→");
                break;
            default:
                aBuilder.SetInnerText(link.DisplayText);
                break;
        }
        liBuilder.InnerHtml = aBuilder.ToString();
        ul.InnerHtml += liBuilder.ToString();
    }

    @Html.Raw(ul)
}

ShowPin.MvcPaging.Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShowPin.MvcPaging.Demo/Views/Shared/_PartialPagingByRoute.cshtml
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>
<table class="table">
    <thead>
        <tr>
            <th>产品名称</th>
            <th>分类名称</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Source)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>
        }
    </tbody>
</table>
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount).Options(o => o.HtmlAttributes(new { @class = "pagination pagination-large" }).RouteName("Pager"))

ShowPin.MvcPaging.Demo/Views/Shared/_ProductGrid.cshtml
@using ShowPin.MvcPaging
@model IPagedList<ShowPin.MvcPaging.Demo.Models.Product>


<table class="table">
    <thead>
        <tr>
            <th>产品名称</th>
            <th>分类名称</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Source)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>
        }
    </tbody>
</table>
@Html.Pager(Model.PageSize, Model.CurrentPage, Model.TotalItemCount, new AjaxOptions() { UpdateTargetId="gridcontainer" }).Options(o => o.HtmlAttributes(new { @class = "pagination pagination-large" }))